// All conferences and their info — reference for SEAMUNs (https://seamuns.site)
// Used by script.js and conference-detail.js. Edit this file to add or update conferences.
window.MUN_CONFERENCES_DATA = [
{
    id: 1,
    name: "MUN07 IV",
    organization: "St Andrews International School, Sukhumvit 107",
    location: "Bangkok, Thailand",
    countryCode: "TH",
    startDate: "2026-03-07",
    endDate: "2026-03-07",
    description: "The fourth annual MUN07 conference at St Andrews International School Sukhumvit 107, featuring 10 diverse committees including specialized bodies and regional organizations.",
    website: "https://mun07.org",
    registrationDeadline: "2026-02-07",
    positionPaperDeadline: "2026-02-14",
    status: "previous",
    size: "250+ attendees",
    generalEmail: "mun07sta@gmail.com",
    munAccount: "@mun07",
    advisorAccount: "mun07sta@gmail.com",
    secGenAccounts: "PJ (@janekij_) and Poon (@natthawit._)",
    parliamentarianAccounts: "Contact via mun07sta@gmail.com",
    pricePerDelegate: "900 THB",
    independentDelsWelcome: true,
    independentSignupLink: "https://forms.gle/cwyjPqszetrQGaNN8",
    advisorSignupLink: "https://forms.gle/xKSp8oSejzXDE6gV7",
    disabledSuitable: true,
    sensorySuitable: true,
    committees: [
        "UNHRC - The Question of Human Rights Abuses in Detention Centres and Prisons in The United States | Head Chair: Tamara (@__.t.petrosyan.__), Deputy Chair: Anai (@anai._.ona)",
        "UNSC - The Question of Preventing Escalation in the Taiwan Strait between Taiwan and China | Head Chair: Flo (@flo.walker.1), Deputy Chair: Agrim (@agrimdaga)",
        "UNOOSA - The Question of Preventing the Weaponisation of Satellites in Outer Space | Head Chair: Rose (@roslyn.ry), Deputy Chair: Tenzin (@tenzinyangring)",
        "SPECPOL - The Question of International Oversight in Yemen's Political Transition with an emphasis on the Houthi Terror Organisation | Head Chair: Kirill (@krlse23), Deputy Chair: Hayeon (@hayeonnkk)",
        "DISEC - The Question of the Use of Drones in Modern Warfare with an emphasis on The Ukraine-Russia War | Head Chair: Vicka (@vicka.w), Deputy Chair: Myesha (@nidhika_s)",
        "USCC - The Question of the Use of the National Guard as a Domestic Policing Force on US Soil | President: Aimie (@aimiea_), Vice President: Budh (@budhman1234)",
        "INTERPOL - The Question of Combating Human Trafficking Networks Along Western Europe with an emphasis on Paris | President: Pund (@pundthepond), Vice President: Ryu (@kior.yu)",
        "ICJ - The Question of the Jorge Glas Dispute in Ecuador v. Mexico | President: Celia (@thatburmesegal), Vice President: Veda (@v3dx_2204)",
        "ASEAN - The Question of Solving the Conflict Between Thailand and Cambodia | Head Chair: Dominic (@dominic_mll), Deputy Chair: Sanvi (@sanvi_k30)",
        "Press Corps - The Question of Combatting Fake News and Disinformation Internationally | Editor in Chief: Su Hyun (@vampyrculture or 28suhyun@regents.ac.th), Editor: Lineysha"
    ],
    uniqueTopics: ["Human Rights Abuses", "Taiwan Strait Conflict", "Space Weaponization", "Yemen Political Transition", "Drone Warfare", "National Guard Policing", "Human Trafficking", "Ecuador v. Mexico Dispute", "Thailand-Cambodia Conflict", "Fake News & Disinformation"],
    chairsPages: "<p>Chair applications contact: mun07sta@gmail.com</p>",
    allocations: ["Thailand", "Singapore", "Malaysia", "Vietnam", "Indonesia", "Philippines", "Brunei", "Myanmar", "Cambodia", "Laos"],
    availableAwards: ["Best Delegate", "Outstanding Delegate", "Honorable Mention", "Best Position Paper", "Best Chair"],
    previousWinners: [],
    schedule: "<p><strong>March 7, 2026:</strong> Full Day Conference - Opening Ceremony, Committee Sessions, Closing Ceremony</p>",
    venueGuide: "<p>Conference held at St Andrews International School, Sukhumvit 107 campus. Wheelchair accessible with access ramps available.</p>",
    extraNotes: "<p>Business attire required. 10 specialized committees including UNHRC, UNSC, UNOOSA, SPECPOL, DISEC, USCC, INTERPOL, ICJ, ASEAN, and Press Corps. <strong>Accessibility:</strong> Wheelchair accessible with ramps available. Sensory-friendly with break room available for delegates who need it. Delegate fee: 900 THB. Follow us on Instagram: @mun07 for updates. Secretary Generals: PJ (@janekij_) and Poon (@natthawit._)</p>"
},
{
    id: 2,
    name: "STAMUN XI",
    organization: "St Andrews International School, High School Campus",
    location: "Bangkok, Thailand",
    countryCode: "TH",
    startDate: "2025-11-16",
    endDate: "2025-11-16",
    description: "The eleventh annual STAMUN conference at St Andrews International School High School Campus, featuring 5 diverse committees covering global issues from drone warfare to mental health.",
    website: "",
    registrationDeadline: "",
    positionPaperDeadline: "",
    status: "previous",
    size: "130 attendees",
    generalEmail: "",
    munAccount: "@munstandrews",
    advisorAccount: "",
    secGenAccounts: "Sarina Luthra",
    parliamentarianAccounts: "",
    pricePerDelegate: "600 THB",
    independentDelsWelcome: false,
    independentSignupLink: "",
    advisorSignupLink: "",
    disabledSuitable: true,
    sensorySuitable: false,
    committees: [
        "DISEC - The Question of Regulating the Use of Drone Weaponry in Modern Warfare | Florence (@flo.walker.1), Dipayan (@dipayanbose911)",
        "WHO - The Question of Strengthening Global Mental Health Infrastructure Post-Pandemic | Meredith (@meredith.x31), Aashirya (@aashirya.2007)",
        "UNESCO - The Question of the Preservation of Cultural Heritage During Armed Conflicts | Agrim (@agrimdaga), Anishka (@ani.nn27)",
        "UNEP - The Question of Combating Ocean Plastic Pollution Through International Collaboration | Jazz (@jazz_atitcha), Fehmiya (@fehmiyaa)",
        "UNHRC - The Question of Safeguarding the rights of refugees in conflict zones | Rosalind (@roslyn.ry), Rosalind (@rosalind.m.p)"
    ],
    uniqueTopics: ["Drone Weaponry Regulation", "Global Mental Health Infrastructure", "Cultural Heritage Preservation", "Ocean Plastic Pollution", "Refugee Rights in Conflict Zones"],
    chairsPages: "",
    allocations: ["United States of America", "United Kingdom", "India", "Thailand", "New Zealand"],
    availableAwards: ["Overall Best Delegate", "Overall Best Chair", "Committee Best Delegate", "Committee Honorable Mention", "Committee Best Position Paper"],
    previousWinners: [],
    schedule: "<p><strong>November 16, 2025:</strong> 8:00 AM - 5:30 PM</p>",
    venueGuide: "<p>Conference held at St Andrews International School, High School Campus. Wheelchair accessible.</p>",
    extraNotes: "<p>Delegate fee: 600 THB. Follow us on Instagram: @munstandrews for updates. Secretary General: Sarina Luthra. <strong>Accessibility:</strong> Wheelchair accessible. Not sensory-friendly.</p>"
},
{
    id: 3,
    name: "THAIMUN XIII",
    organization: "Brighton College",
    location: "Bangkok, Thailand",
    countryCode: "TH",
    startDate: "2026-03-20",
    endDate: "2026-03-22",
    description: "The thirteenth annual THAIMUN conference at Brighton College, featuring 19 diverse committees covering international security, justice, health, and specialized organizations.",
    website: "",
    registrationDeadline: "November 9, 2026",
    positionPaperDeadline: "",
    status: "previous",
    size: "TBD",
    generalEmail: "john.bangkok@hotmail.com",
    munAccount: "@thailandmun",
    advisorAccount: "john.bangkok@hotmail.com",
    secGenAccounts: "John Wood (Founder)",
    parliamentarianAccounts: "Contact via john.bangkok@hotmail.com",
    pricePerDelegate: "3,400 THB",
    independentDelsWelcome: false,
    independentSignupLink: "N/A - Sign-up through school only",
    advisorSignupLink: "Advisors are mandatory - Contact John Wood at john.bangkok@hotmail.com",
    disabledSuitable: true,
    sensorySuitable: false,
    committees: [
        "WHO (World Health Organization) - Topic 1: The Question of Human Challenge Trials as a Means of Accelerating Vaccine Development | Topic 2: The Question of Addressing the 2025 Cholera Outbreak | Chairs: A, B",
        "UNHRC (United Nations Human Rights Council) - Topic 1: The Question of Systemic Racism in the Justice System | Topic 2: The Question of Predictive Policing Technologies | Chairs: A, B",
        "ECOSOC (Economic and Social Committee) - Topic 1: The Question of Addressing the Consequences of the Global Shift Towards Cashless Economies | Topic 2: The Question of Addressing Aid Dependency in Developing States | Chairs: A, B",
        "UNICEF (United Nations Children's Fund) - Topic 1: The Question of Protecting Children Amidst Conflict and Displacement | Topic 2: The Question of Education Access for Adolescent Girls in Afghanistan | Chairs: A, B",
        "UNESCO (United Nations Educational, Scientific and Cultural Organization) - Topic 1: The Question of Regulating Cultural Appropriation in Creative Industries | Topic 2: The Question of Regulating Misinformation Amidst the Rise of 'Edutainment' Platforms | Chairs: A, B",
        "DISEC (Disarmament and International Security Committee) - Topic 1: The Question of Addressing the Militarization of Humanitarian Aid Channels | Topic 2: The Question of Addressing Quantum Computing Arms Race in Military Intelligence | Chairs: A, B",
        "UNODC (United Nations Office of Drugs and Crime) - Topic 1: The Question of Preventing Money Laundering Amidst the Rise of Cryptocurrency | Topic 2: The Question of Implementing International Regulation of Spyware and Surveillance Technology | Chairs: A, B",
        "Arab League - Topic 1: The Question of Addressing the Geopolitical Consequences of New Trade Corridors in the Arab League | Topic 2: The Question of Addressing the US Military Presence in the Arab League | Chairs: A, B",
        "UNSC (United Nations Security Council) - Topic 1: The Question of Addressing the Red Sea Crisis in Yemen | Topic 2: The Question of Addressing the Rise of Terrorist Insurgencies in West Africa | Chairs: A, B",
        "IOC (International Olympic Committee) - Topic 1: The Question of Addressing the Participation of Transgender Athletes in International Sporting Events | Topic 2: The Question of Preventing the Politicization of the Olympic Games in Times of Global Conflict | Chairs: A, B",
        "EP (European Parliament Committee) - Topic 1: The Question of Harmonizing Migration and Asylum Policies in the European Union | Topic 2: The Question of Addressing the Future of European Union Enlargement and Relations with Candidate Countries | Chairs: A, B",
        "Press Corps - Topic 1: The Question of Addressing the Decline of Public Trust in Journalism in the 21st-Century | Chairs: A, B",
        "UKPC (United Kingdom Parliamentary Committee) - Topic 1: The Question of Repealing the Online Safety Act of 2025 | Topic 2: The Question of Assisted Dying Legislation | Topic 3: The Question of Nationalizing British Railways | Chairs: A, B",
        "USCC (United States Congress Committee) - Topic 1: The Question of Imposing Tariffs on Foreign States | Topic 2: The Question of Regulating Legal Immigration | Topic 3: The Question of Providing Military Aid to Foreign States | Chairs: A, B",
        "HSOC (Historical Special Operations Committee) - Topic 1: The Korean War (1950-1953) | Topic 2: The Byzantine Sassanid (602-628 AD) | Chairs: A, B",
        "HCC (Historical Crisis Committee) - Topic 1: The Wars of the Diadochi (321-275 BC) | Topic 2: The Wars of the Three Kingdoms (220-280 AD) | Topic 3: The First Opium War (1839-1842) | Chairs: A, B",
        "ICJ (International Court of Justice) - Topic 1: The Land and Maritime Delimitation and Sovereignty over Islands (Gabon v. Equatorial Guinea, 2023, Advisory) | Topic 2: The Jurisdictional Immunities of the State (Germany v. Italy : Greece Intervening, 2012, Contentious) | Topic 3: The Obligation to Negotiate Access to the Pacific Ocean (Bolivia v. Chile, 2018, Contentious) | Chairs: A, B"
    ],
    uniqueTopics: ["Human Challenge Trials", "2025 Cholera Outbreak", "Systemic Racism in Justice", "Predictive Policing", "Cashless Economies", "Aid Dependency", "Children in Conflict", "Education Access in Afghanistan", "Cultural Appropriation", "Edutainment Misinformation", "Militarization of Aid", "Quantum Computing Arms Race", "Cryptocurrency Money Laundering", "Spyware Regulation", "Arab League Trade Corridors", "US Military Presence", "Red Sea Crisis", "Terrorist Insurgencies", "Transgender Athletes", "Olympic Politicization", "EU Migration Policies", "EU Enlargement", "Public Trust in Journalism", "Online Safety Act", "Assisted Dying", "British Railways", "Foreign Tariffs", "Legal Immigration", "Military Aid", "Korean War", "Byzantine Sassanid", "Wars of the Diadochi", "Three Kingdoms", "First Opium War", "Land Maritime Delimitation", "State Immunities", "Pacific Ocean Access"],
    chairsPages: "<p><strong>Chair Applications:</strong> <a href='https://docs.google.com/forms/d/e/1FAIpQLSe42Wuolo3Rfm2VAKqLEADBTC8ShuMn9gxNOONgw3j5hVqYHQ/viewform' target='_blank'>Apply Here</a> (Deadline: November 9, 2026)</p><p><strong>Photographer Applications:</strong> <a href='https://docs.google.com/forms/d/e/1FAIpQLSe9kwVbuqHHyHLtzz7TS2S13sj3F9Tt50I2IUXlO99nKZaA8w/viewform' target='_blank'>Apply Here</a> (Deadline: February 8, 2026)</p>",
    allocations: ["TBD - Contact conference for country assignments"],
    availableAwards: ["Best Delegate", "Outstanding Delegate", "Honorable Mention", "Best Position Paper"],
    previousWinners: [],
    schedule: "<p><strong>March 20-22, 2026:</strong> Three-day conference - Opening Ceremony, Committee Sessions, Closing Ceremony</p>",
    venueGuide: "<p>Conference held at Brighton College campus. <strong>Accessibility:</strong> Wheelchair accessible. Not sensory-friendly.</p>",
    extraNotes: "<p>Three-day conference featuring 19 committees including traditional UN bodies and specialized organizations. <strong>Registration:</strong> Deadline November 9, 2026. <strong>Independent Delegates:</strong> No - Sign-up through school only. <strong>Advisors:</strong> Advisors are mandatory for all delegations. Contact John Wood at john.bangkok@hotmail.com for advisor registration. <strong>Accessibility:</strong> Wheelchair accessible. Not sensory-friendly. Follow us on Instagram: @thailandmun for updates.</p>"
},
{
    id: 4,
    name: "TSIMUN 2026",
    organization: "TSI Bearing Primary Campus",
    location: "Bangkok, Thailand",
    countryCode: "TH",
    startDate: "2026-01-31",
    endDate: "2026-01-31",
    description: "TSIMUN 2026 at TSI Bearing Primary Campus, featuring 6 diverse committees covering environmental protection, education, health, human rights, technology, and economic development.",
    website: "",
    registrationDeadline: "",
    positionPaperDeadline: "",
    status: "previous",
    size: "150-200 attendees",
    generalEmail: "krishiv.sa.student@tsi.ac.th",
    munAccount: "@tsi.mun",
    advisorAccount: "anishka.na.student@tsi.ac.th",
    secGenAccounts: "Krishiv Savani, Anishka Nag",
    parliamentarianAccounts: "Contact via krishiv.sa.student@tsi.ac.th",
    pricePerDelegate: "600 THB",
    independentDelsWelcome: true,
    independentSignupLink: "",
    advisorSignupLink: "",
    disabledSuitable: false,
    sensorySuitable: false,
    committees: [
        "UNEP - The Question of Addressing the Impact of Waste on Human Health and the Environment | Chairs: A, B",
        "ECOSOC - The Question of Promoting Equal Access to Quality Education Worldwide | Chairs: A, B",
        "WHO - The Question of Combatting Childhood Pneumonia Through Strengthened Health Services | Chairs: A, B",
        "UNHRC - The Question of the Protection of Human Rights in Active Conflict Zones | Chairs: A, B",
        "CSTD - The Question of Establishing Ethical Frameworks for the Global Use of Artificial Intelligence | Chairs: A, B",
        "World Bank - The Question of Ensuring Consumer Protection and Data Privacy in the Expansion of Mobile Banking and Microfinance Services | Chairs: A, B"
    ],
    uniqueTopics: ["Waste Impact on Health", "Equal Access to Education", "Childhood Pneumonia Prevention", "Human Rights in Conflict", "AI Ethics Framework", "Mobile Banking Data Privacy"],
    chairsPages: "<p>Chair applications: <a href='https://docs.google.com/forms/d/e/1FAIpQLSeOKU8_c2gEiqdGmo4snxwNcAIzcXIQ_SyZ3JOLqDjjHExgeQ/viewform' target='_blank'>Apply Here</a></p>",
    allocations: ["TBD - Contact conference for country assignments"],
    availableAwards: ["Best Delegate", "Honorable Mention", "Best Position Paper", "Best Chair"],
    previousWinners: [],
    schedule: "<p><strong>January 31, 2026:</strong> Full Day Conference - Opening Ceremony, Committee Sessions, Closing Ceremony</p>",
    venueGuide: "<p>Conference held at TSI Bearing Primary Campus. <a href='https://maps.app.goo.gl/wP6S1sp1xcHtga3v9?g_st=ipc' target='_blank'>View on Google Maps</a></p>",
    extraNotes: "<p>Delegate fee: 600 THB (Chairs: Free). Follow us on Instagram: @tsi.mun for updates. Secretariat: Krishiv Savani (krishiv.sa.student@tsi.ac.th) & Anishka Nag (anishka.na.student@tsi.ac.th). <strong>Accessibility:</strong> Contact conference for accessibility information.</p>"
},
{
    id: 5,
    name: "KMIDSMUN II",
    organization: "King Mongkut's International Demonstration School",
    location: "KMIDS (King Mongkut's International Demonstration School), Bangkok, Thailand",
    countryCode: "TH",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    description: "The second annual KMIDSMUN conference at King Mongkut's International Demonstration School, featuring diverse committees and welcoming independent delegates.",
    website: "",
    registrationDeadline: "2025-10-25",
    positionPaperDeadline: "",
    status: "previous",
    size: "TBD",
    generalEmail: "rattanapetmattheus@gmail.com",
    munAccount: "@kmidsmun",
    advisorAccount: "rattanapetmattheus@gmail.com",
    secGenAccounts: "Mattheus (rattanapetmattheus@gmail.com) (@sushi_inhaler), Olan (olan.sinsuriya@gmail.com) (@olanbonk)",
    parliamentarianAccounts: "Peach (pidnapak.s@gmail.com) (@papoopi), Unna (sirikorn.kuna@gmail.com) (@unnii.k)",
    pricePerDelegate: "800 THB",
    independentDelsWelcome: true,
    independentSignupLink: "https://forms.gle/vTdnjhx5PhfqkAh59",
    advisorSignupLink: "https://docs.google.com/forms/d/e/1FAIpQLSdxL3s49nq-OjOyfj8QvXQv47SO1dEL1iVoYXsvxWuLl_T-FQ/viewform?fbclid=PAZnRzaANn8_lleHRuA2FlbQIxMQABpwjo4DVYbBSB_JNvacVk0o_xBTRXXGTi_Bme3U652v6O3JzYCepqYQKMxA-I_aem_Nf8AuCkQd1Cld2rNyzNLcA",
    disabledSuitable: true,
    sensorySuitable: true,
    committees: [
        "WHO - The Question of Global Regulation and Access to Gender-Affirming Surgery | Head chair: Dhanwaras (@erng._), Deputy chair: Karn (@karnmightbephotogenic)",
        "UNEP - The Question of the Conservation of Biodiversity and the Protection of Endangered Species | Head chair: Veda (@v3dx_2204), Deputy chair: Yama (@yama.leaung)",
        "UNHRC - The Question of Human Rights Violations Against LGBTQIA+ Individuals | Head chair: Mitra (@luzzysaur), Deputy chair: Mishty (@misht_yy_)",
        "DISEC - The Question of Preventing the Militarization of the Arctic | Head chair: Rosalind (@rosyln.ry), Deputy chair: Emily (@ememiiile)",
        "Press Corps - The Question of Ensuring the Safety of Journalists in the Practice of Journalism | Editor in chief: Pakamol (@noeynw_), Deputy editor in chief: Navan (@n4vvs__)",
        "SPECPOL - The Question of the Global Rise of Religious Nationalism | Head chair: Budh (@budhman1234), Deputy chair: Rawit/Louis (@larrymcchubby)",
        "ICJ - The Question of Allegations of Genocide Against the Rohingya People | Head chair: Celia (@thatburmesegal), Deputy chair: Maprang (@fishy_mp)"
    ],
    uniqueTopics: [
        "The Question of Global Regulation and Access to Gender-Affirming Surgery",
        "The Question of the Conservation of Biodiversity and the Protection of Endangered Species",
        "The Question of Human Rights Violations Against LGBTQIA+ Individuals",
        "The Question of Preventing the Militarization of the Arctic",
        "The Question of Ensuring the Safety of Journalists in the Practice of Journalism",
        "The Question of the Global Rise of Religious Nationalism",
        "The Question of Allegations of Genocide Against the Rohingya People"
    ],
    chairsPages: "<p>Chair applications: <a href='https://docs.google.com/forms/d/e/1FAIpQLSdxL3s49nq-OjOyfj8QvXQv47SO1dEL1iVoYXsvxWuLl_T-FQ/viewform?fbclid=PAZnRzaANn8_lleHRuA2FlbQIxMQABpwjo4DVYbBSB_JNvacVk0o_xBTRXXGTi_Bme3U652v6O3JzYCepqYQKMxA-I_aem_Nf8AuCkQd1Cld2rNyzNLcA' target='_blank'>Apply Here</a></p>",
    allocations: ["TBD - Contact conference for country assignments"],
    availableAwards: ["Best Chair", "Honorable Chair", "Best Delegate (per committee)", "Honorable Mention Delegate (per committee)"],
    previousWinners: [],
    schedule: "<p><strong>January 24, 2026:</strong> Full Day Conference - Opening Ceremony, Committee Sessions, Closing Ceremony</p>",
    venueGuide: "<p>Conference held at KMIDS (King Mongkut's International Demonstration School). Wheelchair accessible and sensory-friendly.</p>",
    extraNotes: "<p>KMIDSMUN II - The second annual MUN conference at King Mongkut's International Demonstration School. Delegate fee: 800 THB. Chair fee: Free. Registration deadline: October 25th, 2025. Independent delegates are welcome. <strong>Accessibility:</strong> Wheelchair accessible and sensory-friendly. Follow us on Instagram: @kmidsmun for updates. Secretary General: Mattheus (@sushi_inhaler). Deputy Secretary General: Olan (@olanbonk). Parliamentarians: Peach (@papoopi) and Unna (@unnii.k).</p>"
},
{
    id: 6,
    name: "HISMUN VI",
    organization: "Harrow International School Bangkok",
    location: "Harrow International School Bangkok",
    countryCode: "TH",
    startDate: "2026-01-31",
    endDate: "2026-01-31",
    description: "The sixth annual HISMUN conference at Harrow International School Bangkok, featuring 6 diverse committees covering topics from ageing global population to AI regulation in outer space.",
    website: "",
    registrationDeadline: "2025-11-30",
    positionPaperDeadline: "",
    status: "previous",
    size: "TBD",
    generalEmail: "",
    munAccount: "@his.mun",
    advisorAccount: "",
    secGenAccounts: "Venice (@vncesque), Noa (@noa.ksit), Tracy (@traacyou)",
    parliamentarianAccounts: "Kwankao (@kwankaochuaphanich), Emery (@ananas_antagonist), Bun (@bun_uthaisang)",
    pricePerDelegate: "800 THB until Nov 30th then 1000 THB",
    independentDelsWelcome: false,
    independentSignupLink: "",
    advisorSignupLink: "",
    disabledSuitable: true,
    sensorySuitable: false,
    committees: [
        "ECOSOC (Beginner) - The Question of Addressing the Economic and Social Impacts of an Ageing Global Population | Chairs: TBD",
        "WHO (Beginner) - The Question of Addressing Barriers to Universal Vaccination in the Post-Pandemic Era | Chairs: TBD",
        "UN WOMEN (Beginner) - The Question of the Welfare and Treatment of Women in Conflict or War Zones | Chairs: TBD",
        "SPECPOL (Intermediate) - The Question of Addressing the Regulation of Artificial Intelligence in Outer Space to Ensure Peaceful Exploration | Chairs: TBD",
        "HSC (Intermediate) - The Question of Addressing the Threat of Nuclear Proliferation and the Establishment of a Hotline Between the United States and the Soviet Union | Chairs: TBD",
        "UNEP (Advanced) - The Question of Addressing Sustainable Solutions for How the International Community can Develop to Combat Water Scarcity in Arid Regions Through Innovation and International Cooperation | Chairs: TBD (This committee will be present unless there are not enough delegates)"
    ],
    uniqueTopics: [
        "Economic and Social Impacts of Ageing Global Population",
        "Barriers to Universal Vaccination in Post-Pandemic Era",
        "Welfare and Treatment of Women in Conflict Zones",
        "Regulation of Artificial Intelligence in Outer Space",
        "Nuclear Proliferation and US-Soviet Hotline",
        "Sustainable Solutions for Water Scarcity in Arid Regions"
    ],
    chairsPages: "",
    allocations: ["TBD - Contact conference for country assignments"],
    availableAwards: [
        "Best Chairs",
        "Honourable Mention for Chairs",
        "Overall Best Delegate",
        "Best Delegate (per committee)",
        "Honourable Mention (per committee)",
        "Best Overall Position Paper"
    ],
    previousWinners: [],
    schedule: "<p><strong>January 31, 2026:</strong> Full Day Conference - Opening Ceremony, Committee Sessions, Closing Ceremony</p>",
    venueGuide: "<p>Conference held at Harrow International School Bangkok. Wheelchair accessible.</p>",
    extraNotes: "<p>HISMUN VI conference featuring 6 dynamic committees with varying difficulty levels. Delegate fee: 800 THB until November 30th, then 1000 THB. Chair fee: Free. <strong>Position Papers:</strong> Position papers are mandatory to be eligible for awards. <strong>Accessibility:</strong> Wheelchair accessible. Not sensory-friendly. The UNEP committee will be present unless there are not enough delegates. Follow us on Instagram: @his.mun for updates. Secretary Generals: Venice (@vncesque), Noa (@noa.ksit), Tracy (@traacyou). Parliamentarians: Kwankao (@kwankaochuaphanich), Emery (@ananas_antagonist), Bun (@bun_uthaisang).</p>"
},
{
    id: 7,
    name: "Newton MUN I",
    organization: "Newton Sixth Form",
    location: "Newton Sixth Form, Siamscape",
    countryCode: "TH",
    startDate: "2026-02-14",
    endDate: "2026-02-15",
    description: "The inaugural Newton MUN conference at Newton Sixth Form, Siamscape, featuring 5 diverse committees covering security, human rights, health, disarmament, and fantasy scenarios.",
    website: "",
    registrationDeadline: "2025-12-31",
    positionPaperDeadline: "",
    status: "previous",
    size: "TBD",
    generalEmail: "",
    munAccount: "@newtonsixthform.mun",
    advisorAccount: "",
    secGenAccounts: "TBD",
    parliamentarianAccounts: "TBD",
    pricePerDelegate: "1500 THB",
    independentDelsWelcome: true,
    independentSignupLink: "",
    advisorSignupLink: "",
    disabledSuitable: true,
    sensorySuitable: true,
    committees: [
        "UNSC (Security Council) - The Question of Strengthening UN Measures to Address Border Disputes, Cultural Heritage Protection, and Civilian Safety in Post-Colonial Boundaries | Chairs: TBD",
        "UNHRC (Human Rights Council) - The Question of Human Rights Legislation in Different Countries that Protects Sex Workers from Discrimination and Destigmatization | Chairs: TBD",
        "WHO (World Health Organization) - The Question of Global Health Standards in Vulnerable and Undeveloped Regions | Chairs: TBD",
        "DISEC (Disarmament and International Security Committee) - The Question of the Prevention of the Accessibility of Cyber Weapons to Terrorist Groups | Chairs: TBD",
        "FWC (Fantasy World Committee) - The Question of Animal Deforestation in the Land of Oz while Settling Territory Disputes (The Wonderful Wizard of Oz) | Chairs: TBD"
    ],
    uniqueTopics: [
        "Border Disputes and Post-Colonial Boundaries",
        "Cultural Heritage Protection",
        "Civilian Safety",
        "Sex Worker Rights and Destigmatization",
        "Global Health Standards",
        "Cyber Weapons and Terrorism",
        "Animal Deforestation in the Land of Oz"
    ],
    chairsPages: "",
    allocations: ["TBD - Contact conference for country assignments"],
    availableAwards: [
        "Best Delegate (per committee)",
        "Honorable Delegate (2 per committee)",
        "Best Position Paper (per committee)",
        "Best Overall Delegate",
        "Best Committee",
        "Honorable Chair",
        "Best Chair"
    ],
    previousWinners: [],
    schedule: "<p><strong>February 14-15, 2026:</strong> Two-day conference - Opening Ceremony, Committee Sessions, Closing Ceremony</p>",
    venueGuide: "<p>Conference held at Newton Sixth Form, Siamscape. Wheelchair accessible and sensory-friendly.</p>",
    extraNotes: "<p>Newton MUN I - The inaugural MUN conference at Newton Sixth Form, Siamscape. Delegate fee: 1500 THB. Chair fee: Free. Delegate applications open from November 1 to December 31, 2025. <strong>Independent Delegates:</strong> Yes, independent delegates are welcome. <strong>Accessibility:</strong> Wheelchair accessible and sensory-friendly. Follow us on Instagram: @newtonsixthform.mun for updates.</p>"
},
{
    id: 8,
    name: "SEAMUN I 2027",
    organization: "SEAMUN",
    location: "Bangkok, Thailand",
    countryCode: "TH",
    startDate: "2027-01-16",
    endDate: "2027-01-17",
    description: "SEAMUN I 2027 — Policies with a Purpose. First student-led multinational independent MUN conference in the region (South East Asian Model United Nations Conference Thailand 2027). Two days in Bangkok with 15 committees across UN bodies, EU Parliament, Press Corps, F1, and crisis formats (UNSC, FWC, HSC). Non-profit conference; all profits donated to TRCS. Target: 370 delegates, 33 chairs, 12 SMT, and 20+ advisors from across South East Asia.",
    website: "https://seamun.com",
    registrationDeadline: "",
    positionPaperDeadline: "",
    status: "upcoming",
    size: "435+ (370 delegates, 33 chairs, 12 SMT, 20+ advisors)",
    generalEmail: "information@seamun.com",
    munAccount: "@seamun.th.conference",
    advisorAccount: "",
    secGenAccounts: "Jules K.A., Secretary-General (juleskittoastrop@gmail.com)",
    parliamentarianAccounts: "",
    pricePerDelegate: "2,500 THB (all delegates). Chair fee: 800 THB",
    independentDelsWelcome: true,
    independentSignupLink: "",
    advisorSignupLink: "",
    smtApplicationLink: "",
    smtApplicationLabel: "",
    fwcFormLink: "",
    fwcFormLabel: "",
    smtRolesHtml: "",
    disabledSuitable: true,
    sensorySuitable: true,
    committeeSizes: [
        { abbrev: "ECOSOC", chairLabel: "Chairs", chairs: 2, delegates: 22, total: 24, gradeRange: "7–12 (Year 8–13)" },
        { abbrev: "F1", chairLabel: "Chairs", chairs: "TBD", delegates: "TBD", total: "TBD", gradeRange: "7–12 (Year 8–13)" },
        { abbrev: "Press Corps", chairLabel: "Editor in Chief, Editor", chairs: 2, delegates: 14, total: 16, gradeRange: "7–12 (Year 8–13)" },
        { abbrev: "UNICEF", chairLabel: "Chairs", chairs: "TBD", delegates: "TBD", total: "TBD", gradeRange: "9–12 (Year 10–13)" },
        { abbrev: "EP", chairLabel: "Chairs", chairs: "TBD", delegates: "TBD", total: "TBD", gradeRange: "7–12 (Year 8–13)" },
        { abbrev: "UNESCO", chairLabel: "Chairs", chairs: "TBD", delegates: "TBD", total: "TBD", gradeRange: "7–12 (Year 8–13)" },
        { abbrev: "UNHRC", chairLabel: "Chairs", chairs: 2, delegates: 23, total: 25, gradeRange: "9–12 (Year 10–13)", gradeNote: "mature topics" },
        { abbrev: "UNODC", chairLabel: "Chairs", chairs: 2, delegates: 22, total: 24, gradeRange: "9–12 (Year 10–13)", gradeNote: "mature topics" },
        { abbrev: "UNSC", chairLabel: "Chairs", chairs: 3, delegates: 15, total: 18, gradeRange: "7–12 (Year 8–13)" },
        { abbrev: "UN Women", chairLabel: "Chairs", chairs: 2, delegates: 22, total: 24, gradeRange: "9–12 (Year 10–13)", gradeNote: "mature topics" },
        { abbrev: "DISEC", chairLabel: "Chairs", chairs: 2, delegates: 23, total: 25, gradeRange: "7–12 (Year 8–13)" },
        { abbrev: "FWC", chairLabel: "Chairs", chairs: 2, delegates: 10, total: 12, gradeRange: "9–12 (Year 10–13)" },
        { abbrev: "HSC", chairLabel: "Chairs", chairs: "TBD", delegates: "TBD", total: "TBD", gradeRange: "7–12 (Year 8–13)" },
        { abbrev: "Interpol", chairLabel: "Chairs", chairs: 2, delegates: 22, total: 24, gradeRange: "9–12 (Year 10–13)" },
        { abbrev: "WHO", chairLabel: "Chairs", chairs: 2, delegates: 22, total: 24, gradeRange: "9–12 (Year 10–13)", gradeNote: "mature topics" }
    ],
    // RoP difficulty badges for SEAMUN I 2027 (from the SEAMUN I 2027 RoP document)
    committeeOverrides: {
        ECOSOC: { difficulty: "beginner" },
        F1: { difficulty: "beginner" },
        "Press Corps": { difficulty: "beginner" },
        UNICEF: { difficulty: "beginner" },
        EP: { difficulty: "intermediate" },
        UNESCO: { difficulty: "intermediate" },
        UNHRC: { difficulty: "intermediate" },
        UNODC: { difficulty: "intermediate" },
        UNSC: { difficulty: "intermediate" },
        "UN Women": { difficulty: "intermediate" },
        DISEC: { difficulty: "advanced" },
        FWC: { difficulty: "advanced" },
        HSC: { difficulty: "advanced" },
        Interpol: { difficulty: "advanced" },
        WHO: { difficulty: "advanced" }
    },
    committees: [
        "ECOSOC (Economic and Societal Council) - The Question of Implementing a Globally Coordinated Universal Basic Income (UBI) Programme as a Strategy for Poverty Eradication and Economic Stability | The Question of Exploring International Mechanisms for Reallocating Military Expenditures Towards the Development and Strengthening of Global Public Health Systems",
        "F1 (Formula One Committee) - The Question of Implementing Durability and Longevity Standards for Critical Car Components to Optimize Component Lifecycles and Minimizing Material and Energy Waste | The Question of Analyzing the Socio-Economic and Infrastructure Impacts of Hosting a New Grand Prix, with a Focus on Mitigating Urban Congestion and Logistics in Highly Populated Cities with a Focus on the Possible F1 Grand Prix of 2028 in Bangkok",
        "Press Corps - The Question of Determining Journalistic Ethics in Reporting on Public Health and Global Affairs.",
        "UNICEF (ESL) - The Question of Strengthening Maternal, Neo-Natal, and Post-Partum Healthcare Systems to Significantly Reduce Preventable Maternal and Infant Mortality and Morbidity | The Question of Recommending Policy Frameworks to Encourage Employer-Supported Flexible Work Arrangements and Parental Leave to Facilitate Early Childhood Development and Strengthen Parent-Child Bonding",
        "EP (European Union) - The Question of Addressing the Socio-Economic Impact of Inflation and the Rising Cost of Living on Vulnerable Populations across Europe | The Question of Standardization in Policies Across Europe to Prevent Poverty Driven Cycles of Crime",
        "UNESCO (UNESCO) - The Question of Developing and Standardizing Inclusive Education Policies and Necessary Accommodations to Ensure Full and Equitable Access to Learning for Neurodivergent Students | The Question of Establishing Guidelines for the Mandatory and Comprehensive Integration of Historical Failures, Atrocities, and Human Rights Violations into National Education Curricula to Promote Reconciliation and Prevent Future Recurrence",
        "UNHRC (ESL) - The Question of Promoting the Standardised Regulation of the Death Penalty and Respect for the Right to Life | The Question of the Obligation to Prevent Cruel, Inhuman, or Degrading Treatments Arising from Deficiencies in the Prison Administrations and Justice Systems",
        "UNODC (United Nations Office on Drugs and Crime) - The Question of Policy Analysis of Alternatives to Conviction and Punishment for Drug Possession for Personal Use | The Question of Addressing the Inter-generational Impact of Substance Abuse and Addiction",
        "UNSC (CRISIS) - The Question of Developing and Standardising Best Practices for Peacekeeping Operations to Ensure Scalable and Sustainable Global Implementation",
        "UN Women (United Nations Entity for Gender Equality and the Empowerment of Women) - The Question of Affirming and Guaranteeing Women's Reproductive Autonomy by Establishing International Legal Standards on Access to Safe and Legal Abortion | The Question of Examining the Recognition of Universal Childcare as a Fundamental Human Right and Its Role in Addressing Declining Birth Rates.",
        "DISEC (Disarmament and International Security Committee) - The Question of Strengthening International Protocols and Logistics for Securing the Cross-Border Transport of Lethal Weapons and Related Materials | The Question of Developing Mechanisms to Prevent the Diversion of Legally Traded Conventional Arms to Illicit Markets and Non-State Actors",
        "FWC (CRISIS) - STRANGER THINGS — The Question of Preventing Harm Caused by Psychic/Psychokinetic Child Experimentation and Ensuring the Protection and Rehabilitation of Gifted Minors | The Question of Addressing the Weaponization of the Human Mind and Establishing International Protocols for the Containment and Non-Proliferation of Psychic Technologies",
        "HSC (CRISIS) - SARS Outbreak (2002-2004) | The Black Death (1346-1353)",
        "Interpol (International Police and Criminal Investigation Organization) - The Question of Combating Transnational Organized Crime in Underground Medical Markets and Unregulated Surgical Practices | The Question of Strengthening Cross-Border Security Frameworks to Mitigate the Nexus of Narcotic Trafficking with a Focus on the Schengen Area and the Golden Triangle",
        "WHO (World Health Organization) - The Question of Examining the Ethical and Regulatory Landscape for the Clinical Use of Psychedelic Drugs in the Treatment of Trauma-Based Mental Health Conditions | The Question of Examining Measures for Combating, Addressing, and Recovering from Pandemics or Severe Outbreaks"
    ],
    uniqueTopics: [
        "Universal Basic Income (UBI)",
        "Reallocating Military Expenditures to Public Health",
        "Durability and Longevity Standards for Critical Car Components",
        "Socio-Economic & Infrastructure Impacts of Hosting a New Grand Prix",
        "Journalistic Ethics in Public Health and Global Affairs",
        "Maternal, Neo-Natal, and Post-Partum Healthcare Systems",
        "Flexible Work Arrangements and Parental Leave",
        "Addressing Inflation and Rising Cost of Living (Europe)",
        "Preventing Poverty-Driven Cycles of Crime (Europe)",
        "Inclusive Education for Neurodivergent Students",
        "Integrating Historical Failures into Education Curricula",
        "Death Penalty Regulation and Right to Life",
        "Preventing Cruel, Inhuman, or Degrading Prison Treatments",
        "Alternatives to Conviction and Punishment for Drug Possession",
        "Inter-generational Impact of Substance Abuse",
        "Peacekeeping Operations Best Practices",
        "Women's Reproductive Autonomy and Safe/Legal Abortion Access",
        "Universal Childcare as a Fundamental Human Right",
        "Cross-Border Transport of Lethal Weapons",
        "Diversion of Conventional Arms to Illicit Markets",
        "Psychic/Psychokinetic Child Experimentation (Stranger Things)",
        "Containment and Non-Proliferation of Psychic Technologies",
        "SARS Outbreak (2002-2004)",
        "The Black Death (1346-1353)",
        "Organized Crime in Underground Medical Markets",
        "Cross-Border Security for Narcotic Trafficking (Schengen/Golden Triangle)",
        "Psychedelic Drugs in Trauma-Based Mental Health",
        "Combating and Recovering from Pandemics or Severe Outbreaks"
    ],
    chairsPages: "<p style=\"margin: 0 0 1rem 0; padding: 10px 14px; background: rgba(30, 136, 229, 0.1); border-left: 4px solid var(--accent-color); border-radius: 6px; font-size: 0.92em;\"><strong>SEAMUN I 2027 — no pages:</strong> This conference does not recruit committee pages. Delegates pass notes digitally through <strong>InterMUN</strong>; there is no paper note-passing or page staff.</p>\n<p>Chairs are expected to be diplomatic, professional, impartial, engaging, calm, creative, empathetic, passionate, decisive, welcoming, punctual, encouraging, and accountable — with additional expectations for ESL and crisis committees (realistic crises, no celebrities).</p>\n<p><strong>Chair report:</strong> High-quality study guide required. Download the <a href=\"../assets/seamun-i-2027-chair-report-template.pdf\" target=\"_blank\" rel=\"noopener noreferrer\">official chair report template (PDF)</a>.</p>\n<p><strong>Chair decisions (SEAMUN I 2027 only):</strong> The chair decisions mechanism applies only to this conference—not other MUNs on SEAMUNs. <a href=\"../assets/seamun-i-2027-chair-decisions.pdf\" download=\"SEAMUN-I-2027-Chair-Decisions.pdf\">Download PDF</a> · <a href=\"../assets/seamun-i-2027-chair-decisions.pdf\" target=\"_blank\" rel=\"noopener noreferrer\">Open in new tab</a> · <a href=\"chair-guide.html#chair-decisions\">View on Chair Guide</a></p>\n<div class=\"template-pdf-preview-wrap template-pdf-preview-wrap--compact\" style=\"margin:12px 0\"><iframe class=\"template-pdf-preview-frame\" title=\"SEAMUN I 2027 Chair Decisions preview\" src=\"../assets/seamun-i-2027-chair-decisions.pdf#view=FitH\"></iframe></div>\n<p><strong>Applications:</strong> <a href=\"https://forms.gle/8UmzMFZP1gEhw9bs9\" target=\"_blank\" rel=\"noopener noreferrer\">Chair application form</a> (also in the <strong>Forms</strong> section).</p>",
    allocations: [
        "TBD"
    ],
    forms: [
        { label: "Chair Application Form", href: "https://forms.gle/8UmzMFZP1gEhw9bs9", icon: "fa-gavel" }
    ],
    availableAwards: [
        "Best Overall Delegate (Trophy)",
        "Best Committee Delegate",
        "Overall Honourable Mention",
        "Committee Honourable Mention",
        "Best Overall Position Paper",
        "Best Committee Position Paper",
        "Best Chair",
        "Honourable Chair Mention",
        "Best Committee",
        "Best Resolution",
        "Best Chair Report"
    ],
    previousWinners: [],
    schedule: "<p><strong>16–17 January 2027</strong> — two-day conference in Bangkok. Committees run on staggered lunch groups (see your committee).</p>\n<details style=\"margin: 0.75rem 0;\"><summary><strong>Group 1</strong> — ECOSOC, UNICEF, F1, Press Corps</summary>\n<p><strong>Day 1:</strong> 07:30 Arrival &amp; registration · 08:30 Opening ceremony · 09:15 Break &amp; photo ops · 09:45 Icebreakers · 10:00 Committee session 1 (motion-focused) · 11:00 Lunch · 12:00 Committee session 2 (resolution writing) · 14:30 Break &amp; resolutions due · 15:00 Committee session 3 (voting procedures) · 16:30 Feedback &amp; delegate departure · 17:00 Chair + SMT departure</p>\n<p><strong>Day 2:</strong> 07:30 Arrival · 08:30 Registration &amp; photo ops · 09:00 Committee session 1 (motion-focused) · 10:00 Break · 10:30 Committee session 2 (motions &amp; resolution writing) · 12:30 Lunch · 13:30 Committee session 3 (resolution writing) · 14:30 Break &amp; resolutions due · 15:00 Committee session 4 (voting procedures) · 16:00 Feedback &amp; break · 16:30 Closing ceremony · 17:30 Photo ops &amp; departure · 18:00 SMT departure</p>\n</details>\n<details style=\"margin: 0.75rem 0;\"><summary><strong>Group 2</strong> — WHO, INTERPOL, HSC, UNSC</summary>\n<p><strong>Day 1:</strong> 07:30 Arrival &amp; registration · 08:30 Opening ceremony · 09:15 Break &amp; photo ops · 09:45 Icebreakers · 10:00 Committee session 1 (motion-focused, 1.5 hr) · 11:30 Lunch · 12:30 Committee session 2 (resolution writing) · 14:30 Break &amp; resolutions due · 15:00 Committee session 3 (voting procedures) · 16:30 Feedback &amp; delegate departure · 17:00 Chair + SMT departure</p>\n<p><strong>Day 2:</strong> 07:30 Arrival · 08:30 Registration &amp; photo ops · 09:00 Committee session 1 (motion-focused) · 10:00 Break · 10:30 Committee session 2 (motions &amp; resolution writing) · 12:15 Lunch · 13:15 Committee session 3 (resolution writing) · 14:30 Break &amp; resolutions due · 15:00 Committee session 4 (voting procedures) · 16:00 Feedback &amp; break · 16:30 Closing ceremony · 17:30 Photo ops &amp; departure · 18:00 SMT departure</p>\n</details>\n<details style=\"margin: 0.75rem 0;\"><summary><strong>Group 3</strong> — UNODC, UN Women, DISEC, FWC</summary>\n<p><strong>Day 1:</strong> 07:30 Arrival &amp; registration · 08:30 Opening ceremony · 09:15 Break &amp; photo ops · 09:45 Icebreakers · 10:00 Committee session 1 (motion-focused, 2 hr) · 12:00 Lunch · 13:00 Committee session 2 (resolution writing) · 14:30 Break &amp; resolutions due · 15:00 Committee session 3 (voting procedures) · 16:30 Feedback &amp; delegate departure · 17:00 Chair + SMT departure</p>\n<p><strong>Day 2:</strong> 07:30 Arrival · 08:30 Registration &amp; photo ops · 09:00 Committee session 1 (motion-focused) · 10:00 Break · 10:30 Committee session 2 (motions &amp; resolution writing, 2 hr 15) · 12:00 Lunch · 13:00 Committee session 3 (resolution writing) · 14:30 Break &amp; resolutions due · 15:00 Committee session 4 (voting procedures) · 16:00 Feedback &amp; break · 16:30 Closing ceremony · 17:30 Photo ops &amp; departure · 18:00 SMT departure</p>\n</details>\n<details style=\"margin: 0.75rem 0;\"><summary><strong>Group 4</strong> — EU Parliament, UNESCO, UNHRC</summary>\n<p><strong>Day 1:</strong> 07:30 Arrival &amp; registration · 08:30 Opening ceremony · 09:15 Break &amp; photo ops · 09:45 Icebreakers · 10:00 Committee session 1 (motion-focused, 2 hr) · 12:30 Lunch · 13:30 Committee session 2 (resolution writing) · 14:30 Break &amp; resolutions due · 15:00 Committee session 3 (voting procedures) · 16:30 Feedback &amp; delegate departure · 17:00 Chair + SMT departure</p>\n<p><strong>Day 2:</strong> 07:30 Arrival · 08:30 Registration &amp; photo ops · 09:00 Committee session 1 (motion-focused) · 10:00 Break · 10:30 Committee session 2 (motions &amp; resolution writing, 2 hr 15) · 11:45 Lunch · 12:45 Committee session 3 (resolution writing) · 14:30 Break &amp; resolutions due · 15:00 Committee session 4 (voting procedures) · 16:00 Feedback &amp; break · 16:30 Closing ceremony · 17:30 Photo ops &amp; departure · 18:00 SMT departure</p>\n</details>",
    venueGuide: "<p>Venue to be announced in Bangkok. Room assignments and arrival instructions will be shared with delegates closer to the conference.</p>\n<p><strong>Accessibility:</strong> Wheelchair accessible and sensory-friendly. A dedicated sensory room with fidget and regulation tools will be available; access is subject to your accommodation application form submission.</p>",
    extraNotes: "<p style=\"margin: 0 0 1rem 0; padding: 10px 14px; background: rgba(255, 193, 7, 0.15); border-left: 4px solid var(--accent-orange, #ff9800); border-radius: 6px; font-size: 0.95em;\"><strong>Planning phase:</strong> Some logistics are still being finalised. Core academic information below is from the official invite package, RoP, and conference documents.</p>\n<p><strong>SEAMUN I 2027 — Policies with a Purpose.</strong> South East Asian Model United Nations Conference Thailand 2027 — the first student-led, multinational independent MUN conference in the region. Hosted in <strong>Bangkok</strong> (venue TBA).</p>\n<p><strong>Mission:</strong> Integrate the MUN circuit in a prestigious and inclusive manner. As a non-profit initiative, SEAMUN promotes professionalism, creativity, and collaboration through a sustainable, high-tech, and unbiased conference. All profits are donated to <strong>TRCS</strong>.</p>\n<p><strong>Grades:</strong> Open to ages 12–18 (Grades 7–12 / Years 8–13), with committee-specific grade ranges. Case-by-case exceptions may be considered.</p>\n<p><strong>Fees:</strong> Delegate 2,500 THB (school and independent) · Chair 800 THB.</p>\n<p><strong>Capacity (target):</strong> 370 delegates, 33 chairs, 12 SMT, and 20+ advisors (435+ total). The conference aims to welcome participants from across South East Asia.</p>\n<p><strong>Advisors:</strong> If more than two delegates or chairs from one institution are attending, they must have an advisor accompanying them.</p>\n<p><strong>Academic:</strong> 15 committees with committee-specific RoP where noted. Three crisis committees: <strong>UNSC</strong>, <strong>FWC (Stranger Things)</strong>, and <strong>HSC</strong>. Position papers are <strong>required for awards eligibility</strong>. Pre-lobbying on substantive topics is prohibited. AI may be used for pre-conference research only — not to generate speeches, papers, or in-committee content (chairs/SMT exempt for admin). Resolutions require 2 main submitters, 2 co-submitters, and at least 15% signatories.</p>\n<p><strong>Dress code:</strong> Western business formal (suits, blazers, dress shirts, formal footwear). No denim, sneakers, or t-shirts during sessions.</p>\n<p><strong>Contact:</strong> General — <a href=\"mailto:information@seamun.com\">information@seamun.com</a> · Secretary-General Jules — <a href=\"mailto:juleskittoastrop@gmail.com\">juleskittoastrop@gmail.com</a>. Instagram: <a href=\"https://www.instagram.com/seamun.th.conference/\" target=\"_blank\" rel=\"noopener noreferrer\">@seamun.th.conference</a> · TikTok: @seamun.th · Line: seamun.th.conference</p>\n<p><strong>Resources:</strong> <a href=\"pages/rop-2027.html\">Rules of Procedure (RoP)</a> · <a href=\"pages/chair-guide.html\">Chair Guide</a> · <a href=\"https://forms.gle/8UmzMFZP1gEhw9bs9\" target=\"_blank\" rel=\"noopener noreferrer\">Chair application form</a>.</p>\n<p><strong>InterMUN:</strong> All conference resources will be available on <strong>InterMUN</strong>, and committee actions will be conducted through the platform—including <strong>digital note passing</strong> (there are no committee pages; paper notes are not used). InterMUN is a platform developed by the Secretary-General to make MUNs easier; RoP is built in to help prevent human errors that may occur during procedure. It also aims to serve as a private mechanism for scoring, note-taking, note passing, and oversight.</p>\n<p><strong>Accessibility:</strong> SEAMUN is <strong>wheelchair accessible</strong> and <strong>sensory-friendly</strong>. We will provide a <strong>dedicated sensory room</strong> with fidget and regulation tools for delegates who need a calmer space. Access to the sensory room is subject to approval based on your <strong>accommodation application form</strong> submission.</p>"
},
{
    id: 9,
    name: "HEXAMUN '26",
    organization: "Lycée Français International de Bangkok (LFIB)",
    location: "Bangkok, Thailand",
    countryCode: "TH",
    startDate: "2026-04-25",
    endDate: "2026-04-25",
    description: "HEXAMUN '26 at Lycée Français International de Bangkok (LFIB). Delegate fee 850 THB; Chair fee 850 THB. Sensory-friendly and wheelchair accessible. Independent delegates welcome.",
    website: "",
    registrationDeadline: "",
    positionPaperDeadline: "",
    status: "previous",
    size: "TBD",
    generalEmail: "",
    munAccount: "@hexa.mun",
    advisorAccount: "",
    secGenAccounts: "Anaïs Amphoux-Ng (anai.amphoux-ng@lfib.ac.th), Eden Romanet (eden.romanet@lfib.ac.th)",
    parliamentarianAccounts: "",
    pricePerDelegate: "850 THB. Chair fee: 850 THB",
    independentDelsWelcome: true,
    independentSignupLink: "https://forms.gle/op4NSAhG4DdJ9nev8",
    advisorSignupLink: "https://forms.gle/LMtMA3DScQyidJXN7",
    disabledSuitable: true,
    sensorySuitable: true,
    committees: [
        "ECOSOC - The Question of Regulating the Influence of Foreign Investment on Developing Economies",
        "HCC - The Indochinese Independence Wars Against French Colonialism",
        "WHO - Tackling Antimicrobial Resistance in Global Health",
        "EU (FR) - La question de la gestion des migrations et des politiques d'asile au sein de l'Union Européenne",
        "PRESS - Addressing the Protection of Journalists in Active Conflict Zones"
    ],
    uniqueTopics: ["Foreign Investment in Developing Economies", "Indochinese Independence Wars", "Antimicrobial Resistance", "EU Migration and Asylum Policies", "Protection of Journalists in Conflict Zones"],
    chairsPages: "",
    allocations: [],
    committeeTags: {
        "EU (FR)": { tag: "In French", tooltip: "This committee is conducted entirely in French for the purpose of including LFIB students." }
    },
    forms: [
        { label: "Page Application Form", href: "https://forms.gle/X5YkB9vRQiFRCEiS8", icon: "fa-file-lines" },
        { label: "Chair Application Form", href: "https://forms.gle/k1iERQmsPqyr4ca27", icon: "fa-gavel" }
    ],
    availableAwards: ["Best Delegate (per committee)", "Honorable Delegate (2 per committee)", "Best Position Paper (per committee)", "Best Overall Delegate", "Honorable Chair", "Best Chair"],
    previousWinners: [],
    schedule: "<p><strong>April 25, 2026 (HEXAMUN 26'):</strong></p><ul style=\"margin: 0.5em 0; padding-left: 1.25em;\"><li>07:30–08:00 — Arrival of delegations</li><li>08:00–09:00 — Opening Ceremony</li><li>09:00–10:25 — First Committee Session</li><li>10:25–10:40 — Snack Break</li><li>10:40–12:30 — Second Committee Session</li><li>12:30–13:30 — Lunch Break</li><li>13:30–15:45 — Third Committee Session</li><li>15:45–16:00 — Snack Break</li><li>16:00–16:30 — Last Committee Session</li><li>16:35–17:10 — Closing Ceremony</li><li>17:10 — End of Conference</li></ul>",
    venueGuide: "<p>Conference at Lycée Français International de Bangkok (LFIB). Wheelchair accessible and sensory-friendly.</p>",
    extraNotes: "<p>HEXAMUN '26. Delegate fee: 850 THB. Chair fee: 850 THB. <strong>Independent Delegates:</strong> Yes. <strong>Accessibility:</strong> Wheelchair accessible and sensory-friendly. Follow us on Instagram: <a href='https://www.instagram.com/hexa.mun/' target='_blank' rel='noopener noreferrer'>@hexa.mun</a>. Secretariat: Anaïs Amphoux-Ng (anai.amphoux-ng@lfib.ac.th), Eden Romanet (eden.romanet@lfib.ac.th).</p>"
},
{
    id: 10,
    name: "RISMUN XIX",
    organization: "Ruamrudee International School",
    location: "Ruamrudee International School Minburi Campus, Thailand",
    countryCode: "TH",
    startDate: "2026-02-28",
    endDate: "2026-03-01",
    description: "RISMUN XIX at Ruamrudee International School Minburi Campus. Two-day conference (Feb 28–Mar 1, 2026) with 11 committees including ECOSOC, UNHRC, IMO, DISEC, Press Corps, INTERPOL, ASEAN (Historical), UNSC, USCC, HCC, and SOC (Special Orwellian Committee). Delegate fee 2,000 THB; Chair & Page fee free. 150+ delegates. Sensory-friendly and wheelchair accessible. Independent delegates welcome; delegate applications via Instagram.",
    website: "",
    registrationDeadline: "",
    positionPaperDeadline: "",
    status: "previous",
    size: "150+ delegates",
    generalEmail: "",
    munAccount: "@ruamrudee_MUN",
    advisorAccount: "",
    secGenAccounts: "Prim S. (prims26@rism.ac.th / @ppr1mm), Voranan (Bene) P. (vorananp26@rism.ac.th / @bean_bene)",
    parliamentarianAccounts: "",
    pricePerDelegate: "2,000 THB",
    independentDelsWelcome: true,
    independentSignupLink: "https://www.instagram.com/ruamrudee_MUN/",
    advisorSignupLink: "",
    disabledSuitable: true,
    sensorySuitable: true,
    committees: [
        "ECOSOC - The Question of Regulating the Purchase of Social Media Company Shares by Governments | The Question of Addressing Youth Unemployment Rates Amidst Global Inflation",
        "UNHRC - The Question of Addressing the Rise of Religious Fundamentalism in the Middle East | The Question of the Right to Protest",
        "IMO - The Question of the Role of Overseas Territories in Determining a Country's Maritime Borders | The Question of Addressing Safety Concerns of Travel Through the Gulf of Aden",
        "DISEC - The Question of Assessing the Threat of Biological Terrorism in Modern Warfare | The Question of Assessing Strategies to Streamline Demining Operations Around the Globe",
        "Press Corps - The Question of Addressing the Ethical and Legal Concerns of Online Government Data Collection of Civilians | The Question of Addressing Concerns of AI-Generated Media in the Press",
        "Interpol - The Question of Combatting Transnational Cybercrime and Ransomware Networks | The Question of Regulating the Proliferation of AI Videos on Social Media Platforms",
        "ASEAN (Historical) - The Question of Addressing Concerns of the Rise of Communism in South East Asia (1975) | The Question of Co-Operation in Recovery from the 1997 Asian Financial Crisis (1998)",
        "UNSC - The Question of Sovereignty over the Jammu and Kashmir Region",
        "USCC - The Question of US Interests Remaining in International Bodies | The Question of Addressing the Issue of Unlawful Entry of Illegal Immigrants into the United States",
        "HCC - The Golden Age of Piracy (1650) | Operation Just Cause (1989)",
        "SOC (Special Orwellian Committee) - The Question of Addressing Diplomatic Ties with East Asia and Eurasia | The Question of Maintaining Order and Security in Airstrip One and the African Disputed Territories"
    ],
    uniqueTopics: [
        "Social Media Company Shares by Governments",
        "Youth Unemployment and Global Inflation",
        "Religious Fundamentalism in the Middle East",
        "Right to Protest",
        "Overseas Territories and Maritime Borders",
        "Safety in the Gulf of Aden",
        "Biological Terrorism in Modern Warfare",
        "Demining Operations",
        "Government Data Collection of Civilians",
        "AI-Generated Media in the Press",
        "Transnational Cybercrime and Ransomware",
        "AI Videos on Social Media",
        "Rise of Communism in Southeast Asia (1975)",
        "1997 Asian Financial Crisis (1998)",
        "Jammu and Kashmir Sovereignty",
        "US Interests in International Bodies",
        "Unlawful Entry of Illegal Immigrants",
        "Golden Age of Piracy (1650)",
        "Operation Just Cause (1989)",
        "SOC Diplomatic Ties and Order in Airstrip One"
    ],
    chairsPages: "",
    allocations: [],
    availableAwards: [],
    previousWinners: [],
    schedule: "<p><strong>Day 1: February 28, 2026</strong></p><ul style=\"margin: 0.5em 0; padding-left: 1.25em;\"><li>08:00–09:00 — Registration &amp; Delegation Photos (60 min) — Redeemer Atrium</li><li>09:00–09:45 — Opening Ceremony (45 min) — PAC</li><li>09:45–10:00 — Transition to Committee Rooms (15 min)</li><li>10:00–11:00 — Committee Session 1 (60 min) — HS Building Committee Rooms</li><li>11:05–11:25 — Break 1 (20 min) — Canteen (HS Side)</li><li>11:30–12:30 — Committee Session 2 (60 min) — HS Building Committee Rooms</li><li>12:30–13:35 — Lunch — Canteen (HS Side)</li><li>13:30–14:30 — Committee Session 3 (60 min) — HS Building Committee Rooms</li><li>14:35–14:50 — Break 2 (15 min) — Canteen (HS Side)</li><li>14:55–16:00 — Committee Session 4 (65 min) — HS Building Committee Rooms</li></ul><p><strong>Day 2: March 1, 2026</strong></p><ul style=\"margin: 0.5em 0; padding-left: 1.25em;\"><li>08:30–09:00 — Delegates arrive — HS Building</li><li>09:00–10:30 — Committee Session 1 (90 min) — HS Building Committee Rooms</li><li>10:35–10:50 — Break (15 min) — Canteen (HS Side)</li><li>10:55–11:55 — Committee Session 2 (60 min) — HS Building Committee Rooms</li><li>11:55–13:00 — Lunch — Canteen (HS Side)</li><li>12:55–13:45 — Committee Session 3 (50 min) — HS Building Committee Rooms</li><li>13:45–14:00 — Goodbyes &amp; transition to PAC (15 min)</li><li>14:00–15:00 — Closing Ceremony (60 min) — PAC</li></ul>",
    venueGuide: "<p>Conference at Ruamrudee International School Minburi Campus. PAC (Performing Arts Centre), HS Building Committee Rooms, Redeemer Atrium, Canteen (HS Side). Wheelchair accessible and sensory-friendly.</p>",
    extraNotes: "<p>RISMUN XIX — Feb 28–Mar 1, 2026. <strong>Fees:</strong> Delegate 2,000 THB; Chair &amp; Page free. <strong>Delegate estimate:</strong> 150+. <strong>Delegate application:</strong> Via Instagram. <strong>Independent Delegates:</strong> Yes. <strong>Accessibility:</strong> Wheelchair accessible and sensory-friendly. Follow us on Instagram: <a href='https://www.instagram.com/ruamrudee_MUN/' target='_blank' rel='noopener noreferrer'>@ruamrudee_MUN</a>. Secretariat: Sec Gen Prim S. (prims26@rism.ac.th / @ppr1mm), Voranan (Bene) P. (vorananp26@rism.ac.th / @bean_bene).</p>"
},
{
    id: 11,
    name: "NTMUN",
    organization: "Student-led",
    location: "Chiang Mai, Thailand",
    countryCode: "TH",
    startDate: "2026-06-13",
    endDate: "2026-06-13",
    description: "TBD",
    website: "",
    registrationDeadline: "TBD",
    positionPaperDeadline: "2026-05-30",
    status: "upcoming",
    size: "TBD",
    generalEmail: "",
    munAccount: "@ntmun.official",
    advisorAccount: "",
    secGenAccounts: "28ylvieschaffranek@lannaist.ac.th",
    parliamentarianAccounts: "TBD",
    pricePerDelegate: "TBD (no higher than 1,200 THB)",
    independentDelsWelcome: true,
    independentSignupLink: "",
    advisorSignupLink: "",
    disabledSuitable: false,
    sensorySuitable: false,
    committees: [
        "UNSC - The Question of Discussing Conflict in the Democratic Republic of the Congo and Implementing Measures to Tackle the Humanitarian Crisis",
        "UNHRC - The Question of Combatting the Systemic Restriction of Women's Rights and Gender-Based Discrimination in Afghanistan Under the Taliban Rule",
        "UNICEF - The Question of Curbing the Spread of Disease and Malnutrition for Children in Warzones",
        "HCC - The American Revolution",
        "FWC (Fantasy World Committee) - Heroes of Olympus: Addressing the Possibility of Conflict between Camp Half-Blood and Camp Jupiter",
        "USCC - The Question of Examining the Conditions, Accountability, and Treatment of Undocumented Immigrants, Particularly Children and Families, within US Detention Facilities Operated by US Immigrations and Customs Enforcement (ICE)"
    ],
    committeeOverrides: {
        UNICEF: { type: "traditional" }
    },
    uniqueTopics: [
        "DRC conflict and humanitarian crisis",
        "Women's rights in Afghanistan",
        "Children in warzones",
        "American Revolution",
        "Heroes of Olympus",
        "ICE detention and immigration"
    ],
    chairsPages: "<p><strong>Chair applications:</strong> <a href='https://docs.google.com/forms/d/e/1FAIpQLSfVnpmkq1LI-ll8J3fov0sUVKkg_53b1k5Sx_BpwsPTB47Ufg/viewform' target='_blank' rel='noopener noreferrer'>Apply via Google Form</a></p>",
    allocations: ["TBD - Contact conference for country assignments"],
    availableAwards: [
        "Best Delegate (per committee)",
        "Honorable Mention (2 per committee)",
        "Best Resolution (GA)",
        "Best Speech (GA)",
        "Best Chairs (committee award)",
        "Overall Best Delegate",
        "Overall Best Position Paper"
    ],
    previousWinners: [],
    schedule: "<p><strong>June 13, 2026:</strong> Full-day conference — schedule TBD.</p>",
    venueGuide: "<p>Conference at <strong>Empress Convention Center</strong>, Chiang Mai, Thailand. <a href='https://www.google.com/maps/search/?api=1&amp;query=Empress%20Convention%20Center%20Chiang%20Mai%20Thailand' target='_blank' rel='noopener noreferrer'>View on Google Maps</a>.</p>",
    extraNotes: "<p><strong>NTMUN</strong> — student-led, Chiang Mai. <strong>Delegate fee:</strong> TBD (no higher than 1,200 THB). <strong>Secretary-General:</strong> <a href='mailto:28ylvieschaffranek@lannaist.ac.th'>28ylvieschaffranek@lannaist.ac.th</a>. Follow <a href='https://www.instagram.com/ntmun.official/' target='_blank' rel='noopener noreferrer'>@ntmun.official</a> on Instagram for updates.</p><p><strong>Key dates (2026):</strong></p><ul style='margin: 0.5em 0; padding-left: 1.25em;'><li><strong>15 April</strong> — Chair applications close</li><li><strong>20 April</strong> — Delegate sign-ups close; chairs announced</li><li><strong>25 April</strong> — Allocations released</li><li><strong>1 May</strong> — Payments due</li><li><strong>5 May</strong> — Chair reports due</li><li><strong>30 May</strong> — Position papers due</li><li><strong>12 June</strong> — Chair and advisor dinner</li><li><strong>13 June</strong> — Conference day</li></ul><p><strong>Independent delegates</strong> are welcome; online signup link will be posted when open. <strong>School/advisor</strong> signup: TBD.</p><p><strong>Accessibility:</strong> Not advertised as wheelchair/mobility accessible; not sensory-friendly — contact organisers if you have access needs.</p>"
}
];

// Prospective conferences (not yet fully registered). Do not include "SEAMUNs" — it is the platform name, not a conference.
window.MUN_PROSPECTIVE_CONFERENCES_DATA = [];

if (typeof window.refreshParticipatingSchoolsFromConferences === 'function') {
    window.refreshParticipatingSchoolsFromConferences();
}
